x=0:10;
y=sin(2*pi/10*x);
plot(x,y);
xtick=get(gca,'xticklabel');
xtick=strcat(xtick,repmat('бу',size(xtick,1),1));
set(gca,'xticklabel',xtick);
ytick=get(gca,'yticklabel');
ytick=strcat(ytick,repmat('%',size(ytick,1),1));
set(gca,'yticklabel',ytick);